### ISSUE TITLE
#2 error on build

### ISSUE THREAD

**Issue by wizidot** [lbke/awesome-vulcan#2]
Hello i've receive this error on my first build after install all packages. So if you could help me to understand   it would be great...
Thanks
I'm on windows with node v8.11.3 en meteor1.8.0.2.
`=> Started proxy.
=> Started MongoDB.
W20190119-19:14:24.087(1)? (STDERR) C:\Users\romai\AppData\Local\.meteor\packages\meteor-tool\1.8.0_2\mt-os.windows.x86_64\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20190119-19:14:24.191(1)? (STDERR)                                             throw(ex);
W20190119-19:14:24.191(1)? (STDERR)                                             ^
W20190119-19:14:24.192(1)? (STDERR)
W20190119-19:14:24.193(1)? (STDERR) Error: **Cannot find module 'react-bootstrap/lib/DropdownItem**'
W20190119-19:14:24.194(1)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20190119-19:14:24.195(1)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20190119-19:14:24.201(1)? (STDERR)     at Object.require (C:\Users\romai\projets\vgt\vgt-app\.meteor\local\build\programs\server\boot.js:288:32)
W20190119-19:14:24.217(1)? (STDERR)     at makeInstallerOptions.fallback (packages\modules-runtime.js:618:18)
W20190119-19:14:24.222(1)? (STDERR)     at Module.require (packages\modules-runtime.js:244:14)
W20190119-19:14:24.222(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\romai\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190119-19:14:24.245(1)? (STDERR)     at Dropdown.jsx (packages/vulcan:ui-bootstrap/lib/components/ui/Dropdown.jsx:1:333)
W20190119-19:14:24.259(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190119-19:14:24.268(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190119-19:14:24.282(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\romai\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190119-19:14:24.305(1)? (STDERR)     at components.js (packages/vulcan:ui-bootstrap/lib/modules/components.js:1:1055)
W20190119-19:14:24.324(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190119-19:14:24.334(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190119-19:14:24.351(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\romai\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190119-19:14:24.373(1)? (STDERR)     at index.js (packages/vulcan:ui-bootstrap/lib/modules/index.js:1:8)
W20190119-19:14:24.393(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190119-19:14:24.398(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190119-19:14:24.415(1)? (STDERR)     at Module.moduleLink [as link] (C:\Users\romai\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
W20190119-19:14:24.420(1)? (STDERR)     at main.js (packages/vulcan:ui-bootstrap/lib/server/main.js:1:8)
W20190119-19:14:24.438(1)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:336:7)
W20190119-19:14:24.458(1)? (STDERR)     at Module.require (packages\modules-runtime.js:238:14)
W20190119-19:14:24.466(1)? (STDERR)     at require (packages\modules-runtime.js:258:21)
=> Exited with code: 1`

**Comment by eric-burel** [comment]
Hi, to my best understanding this is due to the recent update toward React Boostrap 4 alpha version (Vulcan is currently moving toward the last versions of the different libraries, Apollo v2, React Router 4 etc.).
I guess you are using the `devel` branch of Vulcan? If yes then update to the latest commit or post this part on the Slack to get more help:
```
Error: **Cannot find module 'react-bootstrap/lib/DropdownItem**
```
and this part too:
```
(STDERR) at Dropdown.jsx (packages/vulcan:ui-bootstrap/lib/components/ui/Dropdown.jsx:1:333) 
```
Let me know if you are still blocked or if you find a solution.

**Comment by wizidot** [comment]
Many thanks for your answer. actually the problem was on the version of react-bootstrap who was not compatible with the last version of vulcan. I've to upgrade to the beta4 version. 
I encountered a second problem with a the packge autosize-input was not specified with the material-ui package. But ultimatly it's works !
Thanks !

**Comment by eric-burel** [comment]
Glad it helped!
